spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biobac
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
jwt:
  secret: b10bac_super_secret_key_which_is_long_enough_please_change
  expiration-ms: 86400000
services:
  company-url: http://kinomino.ru:8060/api/company
  attribute-url: http://kinomino.ru:8050/api
  user-url: http://kinomino.ru:8070/api
#  user-url: http://localhost:8070/api
