spring:
  application:
    name: warehouseProd
  datasource:
    url: jdbc:mysql://localhost:3306/production?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: biobac_user
    password: rvz!RJKw54qv3S5%
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8082
jwt:
  secret: b10bac_super_secret_key_which_is_long_enough_please_change
  expiration-ms: 86400000
services:
  company-url: http://kinomino.ru/api/company
  attribute-url: http://kinomino.ru/api/attribute
  user-url: http://kinomino.ru/api/users
  #  user-url: http://localhost:8070/api

logging:
  level:
    org.springframework.feign: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG